title: The Workshop on Democratizing Software Verification
description: colocated with the 31st International Conference on Computer-Aided Verification (CAV 2019)
theme: jekyll-theme-cayman
github:
  is_project_page: false
  
