title: The Workshop on<br>Democratizing Software Verification
description: July 14, 2019<br>colocated with<br>The 31st International Conference on Computer-Aided Verification<br>(CAV 2019)
theme: jekyll-theme-cayman
github:
  is_project_page: false
  
